# Generated by Django 3.1.7 on 2021-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeBackgroundImage', models.ImageField(upload_to='media/home')),
                ('HomeVideoFileYoutubeUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='media/keypoints')),
                ('image2', models.ImageField(upload_to='media/keypoints')),
                ('image3', models.ImageField(upload_to='media/keypoints')),
                ('header', models.CharField(max_length=50)),
                ('subtext', models.TextField()),
                ('slug', models.CharField(default='dont_set', max_length=50)),
                ('preview', models.CharField(default='dont_set', max_length=89)),
            ],
        ),
        migrations.CreateModel(
            name='NewsClass',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('level', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('startingGrade', models.IntegerField(default=1)),
                ('endingGrade', models.IntegerField(default=3)),
                ('mainSubText', models.TextField()),
                ('subTextHeader', models.CharField(max_length=40)),
                ('subtext', models.TextField()),
            ],
        ),
    ]
