# Generated by Django 3.1.7 on 2021-04-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('date_posted', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(default='set unique', max_length=50, primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=50)),
                ('Subtext', models.TextField()),
                ('SubHeadingOne', models.CharField(max_length=50)),
                ('SubHeadingOneText', models.TextField()),
                ('SubHeadingTwo', models.CharField(max_length=50)),
                ('SubHeadingTwoText', models.TextField()),
                ('pic1', models.ImageField(default='media/defaults/null_news_image.jpg', upload_to='media/news')),
                ('pic2', models.ImageField(default='media/defaults/null_news_image.jpg', upload_to='media/news')),
                ('pic3', models.ImageField(default='media/defaults/null_news_image.jpg', upload_to='media/news')),
                ('pic4', models.ImageField(default='media/defaults/null_news_image.jpg', upload_to='media/news')),
                ('pic5', models.ImageField(default='media/defaults/null_news_image.jpg', upload_to='media/news')),
                ('slug', models.CharField(default='dont_set', max_length=50)),
                ('NewsClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.newsclass')),
            ],
        ),
    ]
