# Generated by Django 3.1.7 on 2021-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_newsitem_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='preview',
            field=models.CharField(default='dont_set', max_length=89),
        ),
    ]
