# Generated by Django 3.1.7 on 2021-03-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_keypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoint',
            name='slug',
            field=models.CharField(default='slug_not_set', max_length=50),
        ),
    ]
