# Generated by Django 3.1.7 on 2021-03-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_keypoint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoint',
            name='preview',
            field=models.CharField(default='not_set', max_length=89),
        ),
    ]
