# Generated by Django 3.1.7 on 2021-04-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_newsitem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to='media/facilities/page')),
                ('motivationText', models.TextField()),
                ('qoute', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFacility',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('previewImage', models.ImageField(upload_to='media/facilities/items')),
                ('backgroundImage', models.ImageField(upload_to='media/facilities/items')),
                ('qoute', models.TextField()),
                ('header', models.TextField()),
                ('subtext', models.TextField()),
                ('slug', models.TextField(default='dont_set')),
                ('previewText', models.TextField(default='dont_set')),
            ],
        ),
    ]
