# Generated by Django 3.1.7 on 2021-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_auto_20210407_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfacility',
            name='date_posted',
            field=models.DateTimeField(auto_created=True, default='2021-01-01'),
        ),
    ]
