# Generated by Django 3.1.7 on 2021-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_schoolfacility_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfacility',
            name='previewText',
            field=models.CharField(default='dont_set', max_length=214),
        ),
    ]
