# Generated by Django 3.1.7 on 2021-04-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_auto_20210407_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfacility',
            name='date_posted',
            field=models.DateTimeField(auto_created=True, default='2006-10-25 14:30:59'),
        ),
    ]
