# Generated by Django 3.1.7 on 2021-04-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_auto_20210407_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfacility',
            name='date_posted',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
