# Generated by Django 3.1.7 on 2021-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_auto_20210410_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicspagecontent',
            name='welcomeSubtext',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.'),
        ),
    ]
