# Generated by Django 3.1.7 on 2021-04-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_academicspagecontent_welcomesubtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='topstudent',
            name='posted',
            field=models.DateTimeField(null=True),
        ),
    ]
