# Generated by Django 3.1.7 on 2021-04-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_auto_20210411_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('name', models.TextField(default='ECD', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('name', models.TextField(default='Waterpolo', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event', models.TextField(default='This name should be unique, u can do this by adding the date', primary_key=True, serialize=False)),
                ('DateTimeField', models.DateTimeField()),
                ('location', models.TextField(default='Home')),
                ('venue', models.TextField(default='Portland Primary')),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.eventtype')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.sport')),
            ],
        ),
    ]
