# Generated by Django 3.1.7 on 2021-04-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0018_events_eventtype_sport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
