# Generated by Django 3.1.7 on 2021-04-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0019_auto_20210414_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='caption',
            field=models.TextField(default='Girls hockey against Portland'),
        ),
    ]
