# Generated by Django 3.1.7 on 2021-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0021_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.TextField(default='This name should be unique, u can do this by adding the date'),
        ),
    ]
