# Generated by Django 3.1.7 on 2021-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_auto_20210510_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to='media/admissions/page')),
                ('schoolForm', models.FileField(upload_to='media/docs')),
                ('boardingForm', models.FileField(upload_to='media/docs')),
            ],
        ),
    ]
