# Generated by Django 3.1.7 on 2021-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0023_admissionspagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility01_image', models.ImageField(upload_to='media/menu/facilities')),
                ('facility01_text', models.TextField()),
                ('facility02_image', models.ImageField(upload_to='media/menu/facilities')),
                ('facility02_text', models.TextField()),
                ('facility03_image', models.ImageField(upload_to='media/menu/facilities')),
                ('facility03_text', models.TextField()),
                ('facility04_image', models.ImageField(upload_to='media/menu/facilities')),
                ('facility04_text', models.TextField()),
                ('facility05_image', models.ImageField(upload_to='media/menu/facilities')),
                ('facility05_text', models.TextField()),
                ('facility06_image', models.ImageField(upload_to='media/menu/facilities')),
                ('facility06_text', models.TextField()),
                ('menuSubText', models.TextField()),
            ],
        ),
    ]
